version: '3.9'

services:
  # MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - "27017:27017"

  # Node.js API services
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/src/app
    environment:
      PORT: 5000
      MONGO_URL: mongodb://mongo_db:27017
      TEST_DB_URL: mongodb://mongo_db:27017
      DB_NAME: my_todos_db
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
